--
-- Dumping data for table `categorie`
--

INSERT INTO `categorie` (`id`, `title`) VALUES
(1, 'Ecologie'),
(2, 'Technologie'),
(3, 'Nature'),
(4, 'Sciences'),
(5, 'Art');

--
-- Dumping data for table `article`
--

INSERT INTO `article` (`id`, `categorie_id`, `title`, `content`, `created_at`, `user_id`) VALUES
(1, 4, "L'étoile à neutrons", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Amet purus gravida quis blandit turpis cursus in hac habitasse. Ut ornare lectus sit amet. Viverra aliquet eget sit amet tellus cras. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Dignissim diam quis enim lobortis scelerisque fermentum. Et ultrices neque ornare aenean. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Sem integer vitae justo eget magna fermentum iaculis eu non. Suspendisse in est ante in nibh mauris cursus. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Aliquet risus feugiat in ante metus dictum at tempor commodo. Elit ut aliquam purus sit amet luctus venenatis. Quis blandit turpis cursus in. Accumsan lacus vel facilisis volutpat est velit egestas. Nibh cras pulvinar mattis nunc sed blandit libero. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Sit amet porttitor eget dolor morbi non.", "2021-07-22 17:02:21", 1),
(2, 5, "Le musée du Louvre", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est ultricies integer quis auctor elit sed vulputate mi. Vitae purus faucibus ornare suspendisse sed nisi lacus. Nibh tortor id aliquet lectus proin nibh. Morbi tristique senectus et netus. Fringilla est ullamcorper eget nulla. Nunc mi ipsum faucibus vitae aliquet. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Posuere morbi leo urna molestie at elementum eu. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Ac odio tempor orci dapibus ultrices in. Diam in arcu cursus euismod quis viverra nibh. Odio eu feugiat pretium nibh.", "2021-07-14 11:11:14", 1),
(3, 4, "La relativité restreinte", "Le principe de relativité de Galilée, appliqué à la mécanique, faillit être abandonné à la fin du XIXème siècle au moment où les physiciens pensaient mettre en évidence le mouvement de la Terre autour du Soleil par une expérience d’optique. Ils estimaient que la lumière ne pouvait pas se propager dans le vide et invoquaient un milieu particulier permettant cette propagation, qu’ils appelaient alors « l’Ether » (à ne pas confondre avec l’éther des chimistes). Ils s’attendaient à ce que, à la manière de la vitesse du son dans l’air, la vitesse de la lumière dépende de la vitesse de la source par rapport à l’Ether. Cela aurait permis, par exemple, de mettre en évidence le mouvement de la Terre par rapport à l’Ether, et donc d’infirmer la relativité galiléenne. En 1905, Albert Einstein établit la théorie de la relativité restreinte fondant ainsi la notion d’espace-temps et établissant un lien entre l’énergie et la masse. La relativité restreinte fait aussi de la vitesse de la lumière (dans le vide) une grandeur invariante, qui reste inchangée quelle que soit la position de l’observateur. A partir de 1907, il s’attache à décrire la gravitation, à partir de l’idée  simple selon laquelle une personne en chute libre ne sent plus son poids. En 1912, il prolonge cette idée en expliquant que la lumière doit avoir une trajectoire courbée par la gravitation, ce qui sera vérifié lors de l'éclipse du soleil de 1919. Il passera les années suivantes  à mettre au point le formalisme mathématique traduisant ces conceptions. Le 25 novembre 1915, il présente à l’Académie royale de Prusse les équations définitives de la théorie de la relativité générale. Celle-ci s'appuie sur le principe d’équivalence entre gravitation et accélération. L’article correspondant sera publié le 2 décembre.", "2021-07-12 18:43:22", 1),
(6, 3, "Dômes de Miage", "Au départ du Val Montjoie, au sud-est du massif du Mont-Blanc le bassin de Tré-la-Tête est un secteur préservé et sauvage. Il faut 4 à 5 heures pour rejoindre le refuge des Conscrits, qui donne accès aux belles ascensions, mais on ressent ici un isolement assez rare. Les dômes de Miage sont un sommet phare du secteur: d’abord parce qu’ils dominent également la vallée de l’Arve, et que leurs dômes étincellants sont bien visibles de tous. Mais aussi parce que leur ascension est de difficulté technique modeste pour des marcheurs endurants, dans un environnement glaciaire d’exception. Les Dômes de Miage sont très connus dans le massif du Mont-Blanc ; pour débuter l'alpinisme, leur traversée est une grande classique des courses de neige. C'est une arête très esthétique orientée SW - NE qui commence à l'Aiguille de la Bérangère et se termine au Col de Miage. 5 dômes forment cette arête, la traversée intégrale consiste à tous les enchaîner dans le sens E→W ou W→E. Le Col des Dômes, entre le 3e et le 4e, constitue le point milieu de l'arête. Le point culminant de la première partie est appelé sommet W ; le point culminant de la 2e partie et point culminant de l'ensemble est appelé sommet E.", "2021-07-23 09:12:00", 1),
(9, 1, "Encore webpack", "Tristique nulla aliquet enim tortor at auctor urna. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Nisl purus in mollis nunc sed id. Commodo odio aenean sed adipiscing diam. Tortor aliquam nulla facilisi cras fermentum. Quis hendrerit dolor magna eget. Velit ut tortor pretium viverra suspendisse. Enim ut tellus elementum sagittis vitae. Vitae nunc sed velit dignissim sodales ut eu sem integer. Nisl pretium fusce id velit ut tortor pretium. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Sit amet purus gravida quis blandit. Cursus eget nunc scelerisque viverra mauris. Sed turpis tincidunt id aliquet risus feugiat in ante. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Vel eros donec ac odio. Sed tempus urna et pharetra pharetra. Neque egestas congue quisque egestas diam in arcu cursus. Vestibulum lectus mauris ultrices eros in cursus. Ut lectus arcu bibendum at varius vel pharetra. Velit ut tortor pretium viverra suspendisse potenti nullam ac. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Urna porttitor rhoncus dolor purus non. Nisl pretium fusce id velit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Bibendum at varius vel pharetra vel turpis nunc eget. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat. Mauris augue neque gravida in fermentum. Risus nec feugiat in fermentum posuere urna. Eget lorem dolor sed viverra ipsum nunc. Nunc eget lorem dolor sed viverra ipsum nunc.", "2021-07-23 14:07:42", 3),
(10, 2, "Mon chien fugue, pourquoi ?", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Fusce id velit ut tortor pretium viverra. Pharetra diam sit amet nisl suscipit adipiscing. Egestas dui id ornare arcu odio ut sem nulla pharetra. Rhoncus mattis rhoncus urna neque viverra justo nec. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Aliquet enim tortor at auctor urna nunc. Nisi quis eleifend quam adipiscing vitae proin sagittis. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Purus in mollis nunc sed. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Lorem ipsum dolor sit amet consectetur adipiscing. Ullamcorper a lacus vestibulum sed.\r\n\r\nLacus viverra vitae congue eu consequat. Et magnis dis parturient montes. Leo a diam sollicitudin tempor id eu nisl. Scelerisque in dictum non consectetur a erat nam. Ornare massa eget egestas purus viverra. In hac habitasse platea dictumst quisque. Morbi quis commodo odio aenean sed adipiscing diam. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Volutpat maecenas volutpat blandit aliquam etiam erat. Iaculis nunc sed augue lacus. Eros donec ac odio tempor orci dapibus ultrices. Velit euismod in pellentesque massa placerat duis. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Arcu non odio euismod lacinia at quis. Auctor urna nunc id cursus metus aliquam eleifend mi in.", "2021-07-24 12:59:40", 3),
(12, 1, "Les grenouilles de mon jardins", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Fusce id velit ut tortor pretium viverra. Pharetra diam sit amet nisl suscipit adipiscing. Egestas dui id ornare arcu odio ut sem nulla pharetra. Rhoncus mattis rhoncus urna neque viverra justo nec. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Aliquet enim tortor at auctor urna nunc. Nisi quis eleifend quam adipiscing vitae proin sagittis. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Purus in mollis nunc sed. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Lorem ipsum dolor sit amet consectetur adipiscing. Ullamcorper a lacus vestibulum sed. Lacus viverra vitae congue eu consequat. Et magnis dis parturient montes. Leo a diam sollicitudin tempor id eu nisl. Scelerisque in dictum non consectetur a erat nam. Ornare massa eget egestas purus viverra. In hac habitasse platea dictumst quisque. Morbi quis commodo odio aenean sed adipiscing diam. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Volutpat maecenas volutpat blandit aliquam etiam erat. Iaculis nunc sed augue lacus. Eros donec ac odio tempor orci dapibus ultrices. Velit euismod in pellentesque massa placerat duis. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Arcu non odio euismod lacinia at quis. Auctor urna nunc id cursus metus aliquam eleifend mi in.", "2021-07-23 14:14:44", 3),
(18, 5, "Les films d'horreur", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Fusce id velit ut tortor pretium viverra. Pharetra diam sit amet nisl suscipit adipiscing. Egestas dui id ornare arcu odio ut sem nulla pharetra. Rhoncus mattis rhoncus urna neque viverra justo nec. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Aliquet enim tortor at auctor urna nunc. Nisi quis eleifend quam adipiscing vitae proin sagittis. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Purus in mollis nunc sed. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Lorem ipsum dolor sit amet consectetur adipiscing. Ullamcorper a lacus vestibulum sed. Lacus viverra vitae congue eu consequat. Et magnis dis parturient montes. Leo a diam sollicitudin tempor id eu nisl. Scelerisque in dictum non consectetur a erat nam. Ornare massa eget egestas purus viverra. In hac habitasse platea dictumst quisque. Morbi quis commodo odio aenean sed adipiscing diam. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Volutpat maecenas volutpat blandit aliquam etiam erat. Iaculis nunc sed augue lacus. Eros donec ac odio tempor orci dapibus ultrices. Velit euismod in pellentesque massa placerat duis. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Arcu non odio euismod lacinia at quis. Auctor urna nunc id cursus metus aliquam eleifend mi in.", "2021-07-24 10:10:16", 2);

--
-- Dumping data for table `comment`
--

INSERT INTO `comment` (`id`, `article_id`, `content`, `created_at`, `user_id`) VALUES
(2, 1, "J'adore !", "2021-07-24 19:44:15", 3),
(5, 18, "Je te conseil le film Midsommar, il est terrible ! A lundi :)", "2021-07-25 12:49:35", 3),
(11, 18, "Je l'ai vu aussi, il est génial. J'ai mi 2 semaines à m'en remettre !", "2021-07-25 14:17:54", 1),
(13, 1, "Super génial ! C'est trop cool ! Merci !", "2021-07-25 14:39:23", 2),
(14, 1, "Merci à tous !! :)", "2021-07-25 14:40:05", 1),
(15, 6, "I've been there last year with my brother. Such an intense experience ! I'm planning to get back next year, for climbing 'la dent du geant'. Can't wait !", "2021-07-25 15:45:50", 4),
(16, 6, "Superbe course d'alpinisme ! Je vous la conseille (avec un guide surtout !).", "2021-07-25 15:58:46", 7),
(17, 18, "Je l'ajoute à ma liste. Ca donne envie de le voir 😉', '2021-07-25 16:04:06", 7);

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `email`, `roles`, `password`, `firstname`, `lastname`) VALUES
(1, 'davidbreyault@gmail.com', '[\"ROLE_ADMIN\"]', '$2y$13$Fp6Zo.F2bHkNpV3Ccws6uOLtwlUy2hjdD/d26Na3Omtl1.blSN0y.', 'David', 'BREYAULT'),
(2, 'nhipham@gmail.com', '[]', '$2y$13$RJyuKdmEDmqNlousRe1sWOROtjvhIC5uCBv2G98.QpLFrIPFbSC5i', 'Nhi', 'PHAM'),
(3, 'maximediard@gmail.com', '[]', '$2y$13$dczcqclvnAwvUEiXST0GpuP9vek9Q/NstClhr3CzYdJ9vi1pGboPm', 'Maxime', 'DIARD'),
(4, 'john_doe@icloud.com', '[]', '$2y$13$gsum4ma27Wj6Jeo/OFiiMuwdMhqt7ktmjO5P1D1c7/p9Qnq6f4XX6', 'John', 'DOE'),
(5, 'stephen.hawking@yahoo.uk', '[]', '$argon2id$v=19$m=65536,t=4,p=1$QOzNd7T8sq8UG4AlhdNkEQ$IcAkhpAy45Y6lZbBqsZx8wwtKBLvrSMseYLxm5MvR6Y', 'Stephen', 'HAWKING'),
(6, 'jlegrand92@orange.fr', '[]', '$argon2id$v=19$m=65536,t=4,p=1$nQvc92Ay1eFr6h4ZkirTVg$orTckyaDHVMKQEMmUH/ICU5OukTtVRrwYTuYTHpXW1M', 'Jacques', 'LEGRAND'),
(7, 'borisvian@yahoo.fr', '[]', '$2y$13$ISzk0sLZ9qChIrSQHNbgy.G2ob/55cbc0F0DP4DJQqhQEwewm9YrS', 'Boris', 'VIAN');